# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c004bc264d61cfd6bba8516296657ea92024a6685a56716bfb6a897b759c4db415fb7f3b6d054b9ccc05390ae99faf4c99dd32faaf943c5d9d9d86d088ba0a5d

test:
  secret_key_base: 338d220ed0cadbf7f9ba8f75cb4384501a35bf82d5d97c92a02b39efa2d16a1105dad2fe5be4bb057a61f70787e413a74b7bb2ae3911eaa4bde9d55255f916d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
